#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wp7ShareWords
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "Frases#1")]
    public partial class wp7ShareWordsDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void InsertCategoria(Categoria instance);
        partial void UpdateCategoria(Categoria instance);
        partial void DeleteCategoria(Categoria instance);
        partial void InsertFrase(Frase instance);
        partial void UpdateFrase(Frase instance);
        partial void DeleteFrase(Frase instance);
        #endregion

        public wp7ShareWordsDataContext(string connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }


        public wp7ShareWordsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }


        public System.Data.Linq.Table<Categoria> Categorias
        {
            get
            {
                return this.GetTable<Categoria>();
            }
        }

        public System.Data.Linq.Table<Frase> Frases
        {
            get
            {
                return this.GetTable<Frase>();
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute()]
    public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private string _Nome;

        private EntitySet<Frase> _Frases;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        #endregion

        public Categoria()
        {
            this._Frases = new EntitySet<Frase>(new Action<Frase>(this.attach_Frases), new Action<Frase>(this.detach_Frases));
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Nome", DbType = "NVarChar(255)")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                if ((this._Nome != value))
                {
                    this.OnNomeChanging(value);
                    this.SendPropertyChanging();
                    this._Nome = value;
                    this.SendPropertyChanged("Nome");
                    this.OnNomeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK__Frases__000000000000002B", Storage = "_Frases", ThisKey = "Id", OtherKey = "Categoria_Id", DeleteRule = "NO ACTION")]
        public EntitySet<Frase> Frases
        {
            get
            {
                return this._Frases;
            }
            set
            {
                this._Frases.Assign(value);
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_Frases(Frase entity)
        {
            this.SendPropertyChanging();
            entity.Categoria = this;
        }

        private void detach_Frases(Frase entity)
        {
            this.SendPropertyChanging();
            entity.Categoria = null;
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "Frases")]
    public partial class Frase : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private string _Titulo;

        private string _Frases;

        private string _Autor;

        private System.Nullable<int> _Categoria_Id;

        private EntityRef<Categoria> _Categoria;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnTituloChanging(string value);
        partial void OnTituloChanged();
        partial void OnFrasesChanging(string value);
        partial void OnFrasesChanged();
        partial void OnAutorChanging(string value);
        partial void OnAutorChanged();
        partial void OnCategoria_IdChanging(System.Nullable<int> value);
        partial void OnCategoria_IdChanged();
        #endregion

        public Frase()
        {
            this._Categoria = default(EntityRef<Categoria>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Titulo", DbType = "NVarChar(255)")]
        public string Titulo
        {
            get
            {
                return this._Titulo;
            }
            set
            {
                if ((this._Titulo != value))
                {
                    this.OnTituloChanging(value);
                    this.SendPropertyChanging();
                    this._Titulo = value;
                    this.SendPropertyChanged("Titulo");
                    this.OnTituloChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Frases", DbType = "NVarChar(255)")]
        public string Frases
        {
            get
            {
                return this._Frases;
            }
            set
            {
                if ((this._Frases != value))
                {
                    this.OnFrasesChanging(value);
                    this.SendPropertyChanging();
                    this._Frases = value;
                    this.SendPropertyChanged("Frases");
                    this.OnFrasesChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Autor", DbType = "NVarChar(150)")]
        public string Autor
        {
            get
            {
                return this._Autor;
            }
            set
            {
                if ((this._Autor != value))
                {
                    this.OnAutorChanging(value);
                    this.SendPropertyChanging();
                    this._Autor = value;
                    this.SendPropertyChanged("Autor");
                    this.OnAutorChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Categoria_Id", DbType = "Int")]
        public System.Nullable<int> Categoria_Id
        {
            get
            {
                return this._Categoria_Id;
            }
            set
            {
                if ((this._Categoria_Id != value))
                {
                    if (this._Categoria.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnCategoria_IdChanging(value);
                    this.SendPropertyChanging();
                    this._Categoria_Id = value;
                    this.SendPropertyChanged("Categoria_Id");
                    this.OnCategoria_IdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK__Frases__000000000000002B", Storage = "_Categoria", ThisKey = "Categoria_Id", OtherKey = "Id", IsForeignKey = true)]
        public Categoria Categoria
        {
            get
            {
                return this._Categoria.Entity;
            }
            set
            {
                Categoria previousValue = this._Categoria.Entity;
                if (((previousValue != value)
                            || (this._Categoria.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._Categoria.Entity = null;
                        previousValue.Frases.Remove(this);
                    }
                    this._Categoria.Entity = value;
                    if ((value != null))
                    {
                        value.Frases.Add(this);
                        this._Categoria_Id = value.Id;
                    }
                    else
                    {
                        this._Categoria_Id = default(Nullable<int>);
                    }
                    this.SendPropertyChanged("Categoria");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
